### PR TITLE
use it for PostgreSQL

### PR DESCRIPTION
**Pull request by Mortinke**
#1 version which can used for PostgreSQL

### CODE REVIEW

**Comment by ofer-velich** [comment]
It possible to add support to PostgreSQL to this repo.
but not like that, it will break all support for MySQL, need to make ti more generic. you can try and add a argument to for sql engine, and convert all variables and path to take it into account.

**Comment by julian-alarcon** [comment]
@ofer-velich What if you just create a new docker image with the PostgreSQL PR. (logzio-postgresql-logs) and add it to the Data Sources in Logz.io dashboard?
image

**Comment by julian-alarcon** [comment]
I used the code from @Mortinke and created the container for PostgreSQL
https://github.com/julian-alarcon/logzio-postgresql-logs
https://hub.docker.com/r/alarconj/postgresql-logs

**Comment by mirii1994** [comment]
Closing this, since this is an old PR.
In case it's still relevant, please reopen.

**Pull request closed without merging**
